### ISSUE TITLE
Valid byte range should be limited to [0, 128)?

### ISSUE THREAD

**Issue by ematvey** [general-ai-challenge/Round1#2]
In contest description it is stated that agent-environment channels pass byte messages {0, ..., 255}. However it seems that current implementation supports [only valid single-byte UTF-8 characters](https://github.com/general-ai-challenge/Round1/blob/6bd01242f60f9b77fcc7d7a72ffe6bae0ae384cf/src/core/byte_channels.py#L33). 
That is, {0, ..., 127}. Should this be reflected in documentation? Reducing observation/action spaces by half is significant.

**Comment by martinpoliak-goodai** [comment]
That's a good observation there. The public tasks indeed use the lower half of the byte range. We however do not want to promise that the evaluation tasks will do the same - it is possible that the evaluation will introduce tasks that use characters from the upper byte range as well.

**Comment by ematvey** [comment]
Perhaps then we should modify channels to use bytearrays instead of strings, and communicate with agent using 0..255 ints instead of chars? Currently outputting upper half of byte range from an agent is impossible.

**Comment by martinpoliak-goodai** [comment]
We've just tried this - our agent was sending chr(128+i), i > 0, messages and the task saw these answers. Could you please describe in more detail the issue you're having? What is the format of the agent's output you are using? You should be using chr(x) to convert your byte responses to strings before returning them.

**Comment by ematvey** [comment]
I was encoding with `bytes([int_response], encoding='utf-8')` (I figured I should use the same method as serializer does). With `chr()` it would work indeed. Misunderstanding, I guess. Thanks!
