### ISSUE TITLE
Will there be a networked API?

### ISSUE THREAD

**Issue by cookiengineer** [general-ai-challenge/Round1#4]
Hey guys,

I wanted to ask whether the General AI challenge will feature a TCP-based networked API, so that botnets and more advanced ES/HyperNEAT clusters can also take part in the challenge.

As your website states that the simulations-count is the primary ranking criteria for the challenge, I assume that you want to raise an ANN design race that has its focus on efficiency (similar to backprop NEAT, metaQNN et al).

Currently, the tasks and challenges (judging from the demo code) seem to be single-environment only, so it's a bit unfair given the scenario that Evolutionary AIs and Bayesian Learning instructors with parallelized simulations also want to take part in the contest.

Will there be a networked API or a publicly available ranking server for the contest (e.g. similar to SSCAIT)?

**Comment by martinpoliak-goodai** [comment]
Hi cookiengineer,
the first round of the challenge that is currently under way will not feature a TCP-based API. You can implement your own interface on top of the CommAI-env API if you find it useful. Note however that the evaluation will be run on a closed system (an MS Azure PC as described in the specifications). 

It is perfectly fine, though, to train your system using external data or resources that exceed those available at evaluation phase. You will then submit your trained agent along with the data you used for training it. Mind that during evaluation, your agent will not have access to the internet.

Curiously, efficiency is a good thing to have, but what we expect to be even more challenging is actually solving the tasks. The tasks rely on knowledge reuse heavily and solving some of the advanced tasks in the public curriculum is almost impossible without either correct gradual learning implementation or some heavy hard-coded biases. We will filter the heavily biased systems by evaluating the submitted agents on a curriculum different from the public training curriculum.

You are right that the tasks are serial in a single environment. This is a design decision we made. We are aware that it can be challenging for Evolutionary AIs.

Regarding your last question, we are considering having a ranking server for the future challenge rounds, not for this round.

**Comment by FrankBuss** [comment]
Isn't this already possible with RemoteLearner (in src/learners/base.py) ?

**Comment by martinpoliak-goodai** [comment]
Good point, Frank, I forgot about this, it's a feature from the original CommAI-Env. We tested this remote learner recently and found a bug when data is being sent out - we'll issue a bugfix this week.
What remains unchanged, though, is the fact that the evaluation system will be disconnected from the internet - please keep this in mind.

**Comment by cookiengineer** [comment]
@martinpoliak-goodai Where can I find details about the used protocol and its encoding/decoding? It seems to be zeromq behind the scenes, but I couldn't find some details about how the data is actually encoded.

What does the `self.socket.send(str(inp))` and `reply = self.socket.recv()` do? Is this a JSON or a simple float as string value?

For me it is currently unclear what kind of data has to be send to which endpoint in order to train and test my simulation correctly.

**Comment by FrankBuss** [comment]
I didn't test it, but the example from the project from where it was forked looks good:
https://github.com/facebookresearch/CommAI-env#defining-a-learner-in-programming-language-x

**Comment by stranma** [comment]
@cookiengineer 
Hi,

ZeroMQ is available as a library for following programming languages:
C++ | C# | Clojure | CL | Delphi | Erlang | F# | Felix | Go | Haskell | Haxe | Java | Lua | Node.js | Objective-C | Perl | PHP | Python | Q | Racket | Ruby | Scala | Tcl | Ada | Basic | ooc
and maybe more.
If you see your favorite programming language in this list, I would recommend you to use the library in order to avoid the need to know details of commmunication.

Using the library, it is very easy to implement a main loop:
```
r = receive_reward()
i = receive_input()
x = agent_step(r,i)
send_output(x)
```

For example in c#:
```
using ZeroMQ;
...
private ZSocket Environment { get; set; }
...
Environment = new ZSocket(context, ZSocketType.PAIR);
Environment.Connect(address + port);
ZFrame initSendFrame = new ZFrame("hello", Encoding.UTF8);
Environment.SendFrame(initSendFrame);
...
public string ReceiveReward()
    {
        ZFrame rfr = Environment.ReceiveFrame();
        string reward = Encoding.UTF8.GetString(rfr.Read());
        Debug.WriteLine("Received reward: " + reward);
        return reward;
    }
...
```

In case you don't want to use the library or it is not available for your prog. language, info you need is in well written manual [here](http://zeromq.org/intro:read-the-manual). Source codes are available [here](https://github.com/zeromq/libzmq).

Good luck!

**Comment by cookiengineer** [comment]
@martinstrkeenswh My question was more about the expected data frame contents, not about how to use zeromq library itself. So if you expect as a data something like a JSON structure and if so, what are the properties?

So my question was API specific in terms of the AI environment application layer, not zeromq transport layer. Are there API docs for the remote learner API, what it expects and what you can do with it - or do you have to implement everything on your own?

But as @FrankBuss pointed out, it seems to be simple answer/reply utf8 message bus, so that you only send replies to questions with an additional teacher bit that is received afterwards.

**Comment by stranma** [comment]
One important note:
we believe there was a bug in RemoteLearner. It is already fixed, so please pull the changes.

**Comment by stranma** [comment]
@cookiengineer 
As written in [specification](https://mirror.general-ai-challenge.org/challenge_first_round_specifications.pdf) input and output should contain one ASCII character and reward is integer {-1,0,1} (but everything is transmitted as a string, so reward must be parsed on side of the agent).

**Comment by FrankBuss** [comment]
@chopin57otu to be precise, the specification says bytes, see page 14: "Very specifically, the environment sends 8 bits of data to the agent at every simulation step and receives 8 bits
of data from the agent at every simulation step.". The definition of ASCII is a bit fuzzy, but usually it means 7 bits, transported in 8 bits, see https://en.wikipedia.org/wiki/ASCII , unless you mean one of the more modern standardized encodings like ISO-8859-1.

**Comment by martinpoliak-goodai** [comment]
@FrankBuss you are right, the upper 128-255 values are fuzzy in ASCII. In case of the tasks in CommAI-env, we use chr() to convert the bytes to characters, which we then send over the network. We tested this and using the RemoteLearner, we are able to transfer all the byte values in range 0-255 and reconstruct them on the remote side (C# code, eventually using Convert.ToByte to retrieve the bytes from the characters).

You can test whether your remote code is receiving characters correctly by inserting a task which will send all the possible values in range (0-255):

`class MicroTestTask(MicroBase):`

    def __init__(self):
        super(MicroTestTask, self).__init__()

    @on_start()
    def microtest_on_start(self, event):
        self.counter = 0

    def agent_should_know_answers(self):
        return False

    def question_answered(self, is_correct):
        super(MicroTestTask, self).question_answered(is_correct)

    def get_task_generator(self):
        correct_answer = '\xFF'
        parentSelf = self

        def microtest_question(self):
            answer = chr(parentSelf.counter % 255)
            parentSelf.counter += 1
            return answer, correct_answer
        return TaskGenerator(microtest_question)

**Comment by cookiengineer** [comment]
@martinpoliak-goodai Thanks much for clearing it up. I guess the networked API has been answered here, so I'm gonna close this issue if nobody objects?
